### PR TITLE
Fix: Prevent errors when there is whitespace in front of `<?xml ?>`

### PR DESCRIPTION
**Pull request by yisibl**
XMLSyntaxError

```shell
lxml.etree.XMLSyntaxError: XML declaration allowed only at the start of the document
```

### CODE REVIEW

**Comment by yisibl** [comment]
@rsheeter PTAL, thanks!

**Comment by anthrotype** [comment]
actaually i don think picosvg should be responsible for dealing with malformed XML. If it doesn't start with the magic xml header, it's just _not_ XML.

**Comment by anthrotype** [comment]
SVG documents don't have to start with the XML header, and they should not contain one if embedded in an HTML page or another SVG. You should be able to strip the whitespace or the whole xml declaration from your SVG files before passing them on to picosvg.

**Comment by yisibl** [comment]
Okay, that can be closed.

**Pull request closed without merging**
